### ISSUE TITLE
無法使用#include <SocketIoClient.h>

### ISSUE THREAD

**Issue by a5148131** [per1234/ino-troubleshooting#42]
c:\Users\student\Documents\Arduino\libraries\SocketIoClient\SocketIoClient.cpp: In member function 'void SocketIoClient::webSocketEvent(WStype_t, uint8_t*, size_t)':
c:\Users\student\Documents\Arduino\libraries\SocketIoClient\SocketIoClient.cpp:44:4: error: 'hexdump' was not declared in this scope
    hexdump(payload, length);
    ^~~~~~~
    上面說找不到

**Comment by per1234** [comment]
Hi @a5148131. Thanks for your interest in this open source project.

The error you have shared is out of scope for this project due to being too specific. 

We are always happy to provide assistance over on Arduino Forum. Please make a post over there:

https://forum.arduino.cc/

I recommend you write a detailed description of the problem you are having and then use an automated translation service like [**Google Translate**](https://translate.google.com/) to translate it to English before posting on the forum. If you do prefer to communicate in Chinese, you can use the dedicated category in Arduino Forum for that language:

https://forum.arduino.cc/c/international/chinese/75
